### ISSUE TITLE
DSO Toolkit: Web Components

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#827]
De DSO Toolkit is op dit moment een CSS componenten library. Samen met de gedocumenteerde markup geven wij een belofte af over de toegankelijkheid en visuele representatie van een component.

Toen wij eind 2017 de eerste release van de DSO Toolkit uitbrachten was er een heel ander perspectief: Support tot en met IE9 en framework agnostisch. De toolkit wordt door verschillende teams geimplementeerd in React en Angular.

Inmiddels zijn we 3 jaar verder en heeft het programma (zelfs!) IE11 laten vallen. Daarnaast is Fractal, de tool die wij gebruiken om de documentatie en voorgeschreven te genereren in verval geraakt. Het bedrijf (Clearleft) heeft Fractal overgedragen aan _de community_. Fractal v2 gaat niet meer komen, alle effort wordt in v1 gestoken maar een release in het post-Clearleft tijdperk is er nog altijd niet. De DSO Toolkit heeft op dit moment `802 vulnerabilities (786 low, 7 moderate, 8 high, 1 critical)` die niet meer te fixen zijn zonder gebruik te maken van manual resolutions, forks, inchecken of `patch-package`.

De DSO Toolkit is op dit moment niet toekomstvast. En om daar verandering in te brengen gaan we de toolkit doorontwikkelen door de componenten als Web Components te leveren. Daarnaast zullen we de styling voorlopig nog blijven leveren zodat de framework implementaties zullen blijven werken. Met Web Components verschuift de API van _DSO Toolkit CSS compliant markup generen_ naar het aanroepen van een Web Component.

Met de nieuwe DSO Toolkit willen we meer disciplines beter bedienen:
* Implementatoren hoeven niet meer zelf een component te implementeren maar kunnen gebruik maken van Web Components.
* Maintainers en designers: Toolkit maintainers en designers hebben veel meer vrijheid bij het maken en ontwerpen van componenten.
* Implementatoren en maintainers: Minder snel te maken met breaking changes.

Daarnaast willen we tekstschrijvers een betere ervaring geven hoe documentatie wordt gemaakt.

# Status

De beste indicatie is het GitHub Project "Web Components": https://github.com/dso-toolkit/dso-toolkit/projects/10

Issues die in de `master` branch worden opgelost, zullen meegaan in de eerstvolgende milestone. Issues die in `next` worden opgelost komen in de Web Components milestone en worden released zodra `next` naar `master` wordt gemerged.

## Basics

- [x] Grid en Clearfix (#855)

## Componenten

| Status | Component           | styling |   core  | stories (wc) | stories (html) | tests    |         Notities        |
|:------:|---------------------|:-------:|:-------:|--------------|----------------|----------|:-----------------------:|
|        | accordion           |         |         |              |                |          |                         |
|        | alert               | ✔️(#838) | ✔️(#838) | ✔️(#1075)     | ✔️(#1103)               | ✔️(#1075) |                         |
|        | anchor              |         | ❌       |              | #862           |          |                         |
|        | attachments-counter | ✔️(#845) | ✔️(#854) | ✔️(#1075)     |  ✔️(#1104)              |          |                         |
|        | badge               | ✔️(#852) | ✔️(#852) | ✔️(#1075)     | ✔️(#1105)               |          |                         |
|        | banner              | ✔️(#857) | ✔️(#857) | ✔️(#1075)     |  ✔️(#1106)              |          |                         |
|        | breadcrumbs         | ✔️(#1107)        | #858    |              |✔️(#1107)               |          |                         |
|        | button              |         | ❌       |              | #856           |          |                         |
|        | cards               |         |         |              | #921           |          |                         |
|        | conclusion          | ✔️(#1108)        |         |              |  ✔️(#1108)              |          |                         |
| ✔️      | date-picker         | ❌       | ✔️(#877) | ✔️(#1075)     | ❌              | ✔️(#1075) |                         |
|        | definition-list     |✔️(#1112)         | ❌       |              | ✔️(#1112)               |          |                         |
|        | description         | ✔️(#1109)        |         |              | ✔️(#1109)               |          |                         |
|        | dropdown-button     |         |         |              |                |          |                         |
|        | footnotes           | ✔️(#1110)        |         |              | ✔️(#1110)               |          |                         |
|        | form                |         | ❌       |              |                |          |                         |
|        | form-control        | ✔️       | ❌       |              |                |          | .form-control           |
|        | form-elements       |         |         |              |                |          | Per group een component |
|        | form-steps          |         |         |              |                |          |                         |
|        | highlight-box       | ✔️(#863) | ✔️(#863) | ✔️(#1075)     | ✔️(#1111)               |          |                         |
|        | icon                | ✔️(#886) | ✔️(#886) | ✔️(#1075)     |✔️(#1116)               |          |                         |
|        | image               |✔️(#1188)         | ❌       |              |✔️(#1188)                |          |                         |
|        | info                | ✔️(#1148)        |         |              | ✔️(#1148)               |          |                         |
|        | info-button         |         |         |              |                |          |                         |
|        | jumbotron           |         |         |              |(#1206)                |          |                         |
|        | label               | ✔️(#861) | ✔️(#861) | ✔️(#1075)     |✔️(#1117)               |          |                         |
|        | list-button         | (#1250)        |         |              | (#1250)               |          |                         |
|        | lists               |         | ❌       |              |                |          |                         |
|        | logo                |         | ❌       |              | #931           |          |                         |
|        | modal               |         |         |              |                |          |                         |
|        | navigations         | (#1252)        |         |              |(#1252)                |          |                         |
|        | pagination          | (#1254)        |         |              |(#1254)                |          |                         |
|        | panel               |         |         |              |                |          |                         |
|        | progress-bar        | ✔️(#860) | ✔️(#860) | ✔️(#1075)     | ✔️(#1122)                |          |                         |
|        | progress-indicator  |         |         |              |                |          |                         |
|        | rich-content        |         |         |              |                |          |                         |
|        | search-bar          |         | (#864)  |              |                |          |                         |
|        | shopping-cart       |(#1253)         |         |              |(#1253)                |          |                         |
|        | table               | ✔️(#935) | ❌       |              |                |          |                         |
|        | tabs                |         |         |              |                |          |                         |
|        | tooltip             | ✔️(#940) | ✔️(#940) | ✔️(#1075)     |  ✔️(#1123)               |          |                         |
|        | tree-view           |         | (#859)  |              |                |          |                         |
|        | whitebox            |(#1198)         |         |              |(#1198)                |          |                         |

## Automatisering

- [ ] CI/CD (#885)
- [ ] Angular en React wrappers genereren met Stencil Output targets (#915)

# Plan van aanpak

De migratie zal zich over 3 fasen verdelen. Voortgang is via een GitHub project inzichtelijk. Een fase bestaat uit één of meerdere milestones, maar er is geen directe relatie.

Tijdens deze migratie is @tfrijsewijk verantwoordelijk en bereikbaar voor vragen en ondersteuning. Voor inhoudelijke vragen over componenten, documentatie, toegankelijkheid en overige zijn @gofix, @PieterVerheij en @daverhelst beschikbaar.

Wij zijn bereikbaar via deze GitHub of via de DSO Toolkit Slack (invite link op de GitHub repository frontpage).

## Voorbereiding
Voordat er een nieuwe branch (`next`) komt doen we wat voorbereidingen:

- [x] Overstappen naar `yarn` voor met yarn workspaces. Pas in `next` komen er workspaces, maar voor het wisselen tussen `master` en `next` is het voor maintainers makkelijker om niet tussen twee package managers (en node_modules) te hoeven wisselen. Voor implementatoren verandert er niets (#834)
- [x] `bootstrap-sass` inchecken onder `/libs` ipv als dependency in `package.json` (#835)

## Migratie
Tijdens deze fase is het belangrijk dat `next` up to date blijft met `master`. Tijdens de migratie zullen we nog steeds features opleveren. Vanaf deze fase komen er releases uit op dso-toolkit.nl en NPM onder de dist-tag `next`.

- [x] Alle changes in `master` direct upstream mergen naar `next`
- [x] Nieuwe branch `next` (#837)
- [x] Bootstrap ongebruikte files opschonen (#853)
- [x] Yarn workspaces inrichten voor `@dso-toolit/core`, `@dso-toolkit/styling` en `dso-toolkit` (#836)
- [x] `@dso-toolkit/css`: CSS implementatie van het DSO Design System in SCSS naar CSS. Build artifacts: 1 CSS per SCSS component en `dso-icons.svg`
- [ ] `@dso-toolkit/css` build voorzien van Autoprefixer
- [x] `@dso-toolkit/core`: Storybook. Dependency naar `@dso-toolkit/styling` (#1075)
- [ ] Een issue per component in Fractal:
  * van nunjucks naar custom element in `@dso-toolkit/core`
  * Alle varianten uit de `component.config.yml` renderen met `@dso-toolkit/core` component hydration
  * styling samenvoegen uit `bootstrap-sass` en `dso-toolkit` naar SCSS stylesheet in `@dso-toolkit/styling`
  * `dso.scss`: verwijzingen naar styling uit `bootstrap-sass` en `dso-toolkit` vervangen met `@dso-toolkit/styling`
  * Documentatie opsplitsen in maintainers documentatie (Storybook), implementatie documentatie (naast Fractal component) en Web Component documentatie (naast StencilJS component)
- [x] Statificeren voor markup voorschriften (#888)

## Afronden
- [x] `next` naar `master` mergen.
- [x] `.gitignore` opruimen (#914)
- [ ] Fractal vervangen met een waardig alternatief zoals Docusaurus, docsify of Gatsby. Documentatie uit Fractal gaat in één keer over.
- [ ] `dso-toolkit` package deprecaten. Implementatoren moeten over naar `@dso-toolkit/styling`. API en eindresultaat blijft gelijk.

# Research

De afgelopen periode hebben we op verschillende gebieden onderzoek gedaan. Hieronder een (incomplete) uiteenzetting van het een en ander

## StencilJS

Het _maken_ van Web Components in niet per se "leuk". Daarom schrijven we geen Web Components maar StencilJS Components welke door de Stencil compiler worden omgezet naar Web Components. Tijdens de run-time van het Web Component is er geen StencilJS actief, StencilJS zet zichzelf ook neer als toolchain en niet als framework.

Naast Stencil hebben we naar de volgende oplossingen gekeken:
* LitElement met lit-html
* Solid
* Lightning Web Components

## Fractal alternatief

* https://docsify.js.org/#/
* https://docusaurus.io/
* https://www.gatsbyjs.com/

**Comment by timveld** [comment]
Moet ik bepaalde nieuwe tools op toegankelijkheid checken? Voor de backend (dingen als Yarn) lijkt me dat niet zo nodig maar het fractal alternatief heeft vermoedelijk wel impact op de weergave van de documentatie. Zo ja: naar welke tools moet ik een onderzoek doen, zijn alle 3 genoemde fractal alternatieven serieus in de race? En andere tools?

**Comment by tfrijsewijk** [comment]
Een alternatief voor Fractal gaat pas over 2 tot 3 maanden spelen, de 3 in het lijstje staat er eerder dat ik ze niet vergeet. Voor nu is er geen onderzoek nodig, maar ik houd je in de loop

**Comment by PieterVerheij** [comment]
"Form steps" heet inmiddels "Application header"

**Comment by hansgrimm** [comment]
@tfrijsewijk ik zie dat de laatste actie op deze issue ruim een jaar geleden was, en ik heb het vermoeden dat dit links en rechts is ingehaald door onder meer Toolkit Next. Kan deze dicht of heb je hier nog plannen mee?

**Comment by hansgrimm** [comment]
@tfrijsewijk ^^ 😉

**Comment by tfrijsewijk** [comment]
Ik ben er nog niet aan toe om afscheid van dit issue te nemen 😭

**Comment by hansgrimm** [comment]
Dan laat ik ‘m leven 😎

**Comment by tfrijsewijk** [comment]
@hansgrimm OK ik heb afscheid genomen.
